database:
  test:
    name: "flying_apk_test.db"
  development:
    name: "flying_apk_development.db"
  production:
    name: "flying_apk"
    host: "localhost"
    user: "root"
    password: "1234567"
directories:
  public: "./public"
  apk_files: "./public/files"
security:
  test:
    password_salt: "IknowThatIKnowNothing"
  development:
    password_salt: "IknowThatIKnowNothing"
  production:
    # Here, value of password_salt must be changed
    password_salt: "IknowThatIKnowNothing"
mail:
  smtp:
    address: "smtp.example.com"
    port: 465
    user_name: "user@example.com"
    password: "1234567"
    authentication: "plain"
    enable_starttls_auto: true
    tls: false
  sender: "user@example.com"
